name: Build and release ICU


on:
  push:
    branches:
    - master
    tags:
    - v*


jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      run: ./build.sh

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-linux
        path: "*.tar.xz"


  build-windows:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: recursive

    - name: Set up MSYS2 PATH
      run: echo C:\msys64\usr\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build
      run: ./build.sh
      shell: bash --login -eo pipefail "{0}"
      env:
        MSYSTEM: MINGW64
        CHERE_INVOKING: 1
        MSYS2_PATH_TYPE: inherit

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-windows
        path: "*.tar.xz"


  build-macos:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      run: ./build.sh

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-macos
        path: "*.tar.xz"


  release:
    if: startsWith(github.ref, 'refs/tags/')

    needs:
    - build-linux
    - build-windows
    - build-macos

    runs-on: ubuntu-20.04
    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          artifacts/release-linux/*.tar.xz
          artifacts/release-windows/*.tar.xz
          artifacts/release-macos/*.tar.xz
